services:
  mongo:
    image: mongo:7
    container_name: sg-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: supremegaming

  mongo-express:
    image: mongo-express:1
    container_name: sg-mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: 'false'
    depends_on:
      - mongo

volumes:
  mongo-data:
