import { GameServer } from '@supremegaming/common/interfaces';

export const servers = [
  {
    host: 'play.supremegaming.gg',
    port: 28034,
    rcon_port: 18034,
    map_name: 'Aberration PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28036,
    rcon_port: 18036,
    map_name: 'Center PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28038,
    rcon_port: 18038,
    map_name: 'Crystal Isles PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28040,
    rcon_port: 18040,
    map_name: 'Extinction PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28042,
    rcon_port: 18042,
    map_name: 'Fjordur PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28044,
    rcon_port: 18044,
    map_name: 'Genesis PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28046,
    rcon_port: 18046,
    map_name: 'Genesis 2 PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28048,
    rcon_port: 18048,
    map_name: 'Island PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28050,
    rcon_port: 18050,
    map_name: 'Ragnarok PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28052,
    rcon_port: 18052,
    map_name: 'Scorched Earth PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28054,
    rcon_port: 18054,
    map_name: 'Valguero PVE',
    game: 'ark',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28010,
    rcon_port: 18010,
    map_name: 'PF Ragnarok PVE',
    game: 'ark-pf',
  },
  {
    host: 'play.supremegaming.gg',
    port: 28024,
    rcon_port: 18024,
    map_name: 'PF Crystal Isles PVE',
    game: 'ark-pf',
  },
  {
    host: 'play.supremegaming.gg',
    port: 29000,
    rcon_port: 19000,
    map_name: 'Supreme Siptah',
    game: 'conan',
  },
  {
    host: 'play.supremegaming.gg',
    port: 29002,
    rcon_port: 19002,
    map_name: 'Supreme Calamitous RP-Lite',
    game: 'conan',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57500,
    rcon_port: 17000,
    map_name: 'A1',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57502,
    rcon_port: 17002,
    map_name: 'A2',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57504,
    rcon_port: 17004,
    map_name: 'A3',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57506,
    rcon_port: 17006,
    map_name: 'A4',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57508,
    rcon_port: 17008,
    map_name: 'A5',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57510,
    rcon_port: 17010,
    map_name: 'A6',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57512,
    rcon_port: 17012,
    map_name: 'A7',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57514,
    rcon_port: 17014,
    map_name: 'A8',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57516,
    rcon_port: 17016,
    map_name: 'B1',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57518,
    rcon_port: 17018,
    map_name: 'B2',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57520,
    rcon_port: 17020,
    map_name: 'B3',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57522,
    rcon_port: 17022,
    map_name: 'B4',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57524,
    rcon_port: 17024,
    map_name: 'B5',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57526,
    rcon_port: 17026,
    map_name: 'B6',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57528,
    rcon_port: 17028,
    map_name: 'B7',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57530,
    rcon_port: 17030,
    map_name: 'B8',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57532,
    rcon_port: 17032,
    map_name: 'C1',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57534,
    rcon_port: 17034,
    map_name: 'C2',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57536,
    rcon_port: 17036,
    map_name: 'C3',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57538,
    rcon_port: 17038,
    map_name: 'C4',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57540,
    rcon_port: 17040,
    map_name: 'C5',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57542,
    rcon_port: 17042,
    map_name: 'C6',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57544,
    rcon_port: 17044,
    map_name: 'C7',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57546,
    rcon_port: 17046,
    map_name: 'C8',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57548,
    rcon_port: 17048,
    map_name: 'D1',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57550,
    rcon_port: 17050,
    map_name: 'D2',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57552,
    rcon_port: 17052,
    map_name: 'D3',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57554,
    rcon_port: 17054,
    map_name: 'D4',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57556,
    rcon_port: 17056,
    map_name: 'D5',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57558,
    rcon_port: 17058,
    map_name: 'D6',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57560,
    rcon_port: 17060,
    map_name: 'D7',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57562,
    rcon_port: 17062,
    map_name: 'D8',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57564,
    rcon_port: 17064,
    map_name: 'E1',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57566,
    rcon_port: 17066,
    map_name: 'E2',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57568,
    rcon_port: 17068,
    map_name: 'E3',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57570,
    rcon_port: 17070,
    map_name: 'E4',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57572,
    rcon_port: 17072,
    map_name: 'E5',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57574,
    rcon_port: 17072,
    map_name: 'E6',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57576,
    rcon_port: 17076,
    map_name: 'E7',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57578,
    rcon_port: 17078,
    map_name: 'E8',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57580,
    rcon_port: 17080,
    map_name: 'F1',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57582,
    rcon_port: 17082,
    map_name: 'F2',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57584,
    rcon_port: 17084,
    map_name: 'F3',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57586,
    rcon_port: 17086,
    map_name: 'F4',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57588,
    rcon_port: 17088,
    map_name: 'F5',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57590,
    rcon_port: 17090,
    map_name: 'F6',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57592,
    rcon_port: 17092,
    map_name: 'F7',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57594,
    rcon_port: 17094,
    map_name: 'F8',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57596,
    rcon_port: 17096,
    map_name: 'G1',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57598,
    rcon_port: 17098,
    map_name: 'G2',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57600,
    rcon_port: 17100,
    map_name: 'G3',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57602,
    rcon_port: 17102,
    map_name: 'G4',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57604,
    rcon_port: 17104,
    map_name: 'G5',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57606,
    rcon_port: 17106,
    map_name: 'G6',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57608,
    rcon_port: 17108,
    map_name: 'G7',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57610,
    rcon_port: 17110,
    map_name: 'G8',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57612,
    rcon_port: 17112,
    map_name: 'H1',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57614,
    rcon_port: 17114,
    map_name: 'H2',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57616,
    rcon_port: 17116,
    map_name: 'H3',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57618,
    rcon_port: 17118,
    map_name: 'H4',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57620,
    rcon_port: 17120,
    map_name: 'H5',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57622,
    rcon_port: 17122,
    map_name: 'H6',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57624,
    rcon_port: 17124,
    map_name: 'H7',
    game: 'atlas',
  },
  {
    host: 'play.supremegaming.gg',
    port: 57626,
    rcon_port: 17126,
    map_name: 'H8',
    game: 'atlas',
  },
] as GameServer[];
