# Compose file for local testing
# Same can be used for production, just swap out the image name
#
# To run:
#   docker-compose -f dev.docker-compose.yml --env-file .env.local up -d

name: ini-notifier-node
services:
  dev:
    image: ini-notifier-node:latest
    container_name: ini-notifier-node
    restart: always
    environment:
      INI_URL: ${INI_URL}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      POLL_INTERVAL_MS: ${POLL_INTERVAL_MS}
      REQUEST_TIMEOUT_MS: ${REQUEST_TIMEOUT_MS}
      NOTIFIER_NAME: ${NOTIFIER_NAME}
      NOTIFY_ON_STARTUP: ${NOTIFY_ON_STARTUP}
      CACHE_DIR: ${CACHE_DIR}
      EMBED_TITLE: ${EMBED_TITLE}
      EMBED_COLOR: ${EMBED_COLOR}
    volumes:
      - ./.cache:/data
