name: Build Affected

on:
  workflow_call:

jobs:
  build:
    name: Affected
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Affected
        run: npx nx affected:build --configuration=production --exclude=ark-cacher-node,conan-cacher  --base=origin/development --parallel=2

        # Iterate through the dist folder and for any folder in dist/apps that has the suffix "-nest",
        # copy the root package.json to the /app/<project-name> folder.
        #
        # This is necessary because as of this version of Nx, it cannot reliably generate a package.json for NestJS applications.
        # and the more common issue is missing required database drivers.
      - name: Inject Package JSON
        run: |
          shopt -s nullglob

          # Check if dist/apps exists
          if [ ! -d dist/apps ]; then
            echo "dist/apps does not exist"
            exit 0
          fi

          for d in dist/apps/*-nest; do
            echo "Copying package.json to $d"
            cp package.json "$d"
          done

          echo ""
          echo "Listing dist/apps"
          ls dist/apps/

          shopt -u nullglob

        # Static angular applications can have environment variables injected at container runtime using the
        # tokenSubstitute.sh script. This script is copied to the dist/apps/<project-name>-angular folder.
        #
      - name: Inject Token Subsitution Script
        run: |
          shopt -s nullglob

          # Check if dist/apps exists
          if [ ! -d dist/apps ]; then
            echo "dist/apps does not exist"
            exit 0
          fi

          for d in dist/apps/*-angular; do
            echo "Copying tokenSubstitute.sh to $d"
            cp scripts/ci/tokenSubstitute.sh "$d"
          done

          echo ""
          echo "Listing dist/apps"
          ls dist/apps/

          shopt -u nullglob

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: dist/
