# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development Deploy

on:
  workflow_call:
    secrets:
      SERVER_SSH_KEY:
        required: true
      REMOTE_HOST:
        required: true
      REMOTE_USER:
        required: true
      REMOTE_TARGET:
        required: true

jobs:
  Development:
    runs-on: ubuntu-latest
    name: Deploy to Server

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: '${{ github.sha }}/dist/apps/supremegaming-angular/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{secrets.REMOTE_TARGET}}
          ARGS: '-rltgoDzvO --delete'
