# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development Build

on:
  workflow_call:

jobs:
  build:
    name: Development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Supreme Gaming Website
        run: npx nx run supremegaming-angular:build:production

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: dist/
