# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Server

    steps:
      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: 'dist/apps/supremegaming-angular/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{secrets.REMOTE_TARGET}}
          ARGS: '-rltgoDzvO --delete'
